##===- projects/bytesflops/lib/include/Makefile -----------------*- Makefile -*-===##

###################################
# Build the LLVM common includes  #
# (part of the Bytesflops tool)	  #
#				  #
# By Scott Pakin <pakin@lanl.gov> #
###################################

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Distribute the contents of this directory.
#
EXTRA_DIST = byfl-common.h

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
