=head1 NAME

bfbin2sqlite3 - convert Byfl output to a SQLite3 database file

=head1 SYNOPSIS

B<bfbin2sqlite3> I<input_file.byfl> [I<output_file.db>]

=head1 DESCRIPTION

By default, applications instrumented with Byfl write measurement data
to a binary F<.byfl> file.  B<bfbin2sqlite3> converts such files to
SQLite3 database files.  These can be loaded directly into the
B<sqlite3> command-line database tool or converted into other
spreadsheet formats.

=head1 OPTIONS

B<bfbin2sqlite3> has no command-line options.  The program accepts the
name of a F<.byfl> file to read and a SQLite3 database file to create.
If not specified, the name of the database file will be the same as
that of the input file but with F<.byfl> replaced with F<.db>.  (If the
file name does not end in F<.byfl> then F<.db> will be appended to the
file name.)

=head1 EXAMPLES

The simplest usage is just

    $ bfbin2sqlite3 myprog.byfl

which produces F<myprog.db>.

If the F<.byfl> file is expected to be used only to produce the
SQLite3 database and then deleted, one can save time and disk space by
writing Byfl binary output to a named pipe and running
B<bfbin2sqlite3> on that named pipe:

    $ mkfifo myprog.pipe
    $ bfbin2sqlite3 myprog.pipe myprog.db &
    $ env BF_BINOUT=myprog.pipe ./myprog
    $ rm myprog.pipe

=head1 SEE ALSO

sqlite3(1), bfbin2csv(1), bfbin2hdf5(1), bfbin2xmlss(1), bf-clang(1),
bf-clang++(1), bf-gcc(1), bf-g++(1), bf-gfortran(1), bf-gccgo(1),
L<the Byfl home page|https://github.com/losalamos/Byfl/>, L<the SQLite
home page|http://www.sqlite.org/>

=head1 AUTHOR

Scott Pakin, I<pakin@lanl.gov>
