##===- projects/bytesflops/lib/Makefile ------------------------*- Makefile -*-===##

###################################
# Build the LLVM bytesflops pass  #
# and run-time library            #
# (part of the Bytesflops tool)	  #
#				  #
# By Scott Pakin <pakin@lanl.gov> #
###################################

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=bytesflops byfl include

include $(LEVEL)/Makefile.common
