##===- projects/bytesflops/tools/Makefile ------------------------*- Makefile -*-===##

#########################################
# Build various utilities that          #
# facilitate use of the Bytesflops tool #
#				        #
# By Scott Pakin <pakin@lanl.gov>       #
#########################################

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=postproc wrappers

include $(LEVEL)/Makefile.common
